image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

job:
  stage: build
  script:
    - echo "I'm a job"



# Dynamic Application Security Testing
nmap:
  stage: integration
  script:
    - docker pull hysnsec/nmap
    - docker run --rm -v $(pwd):/tmp hysnsec/nmap -h prod-s3zfidv9 -o /tmp/nmap-output.xml
  artifacts:
    paths: [nmap_output.xml]
    when: always
