image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

job:
  stage: build
  script:
    - echo "I'm a job"

secrets-scanning:
  stage: build
  script:
    - docker pull hysnsec/detect-secrets
    - docker run --rm -v $(pwd)/tmp/ :/ hysnsec/detect-secrets scan  /$(pwd)/tmp/detect-secrets.json
  artifacts:
    paths: [detect-secrets.json]
    when: always



#os-hardening:
  #stage: prod
  #only:
   # - main
  #script: 
   # - echo "this is my attempt to harden"
  #allow_failure: true
  #artifacts:
  #  paths: [os-hardening.json]

  


# Dynamic Application Security Testing
#nmap:
  #stage: integration
  #script:
   # - docker pull hysnsec/nmap
    #- docker run --rm -v $(pwd):/tmp hysnsec/nmap -h devsecops-box-s3zfidv9 -o /tmp/nmap-out.xml
  #artifacts:
   # paths: [nmap_out.xml]
    #when: always
